name: Python Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Check formatting with Black
      run: uv run black --check .

    - name: Check types with Pyright
      run: uv run pyright .

    - name: Run tests
      run: uv run pytest